name:                sparep-api-gen
version:             0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - genvalidity
    - genvalidity-appendful
    - genvalidity-text
    - sparep-api
    - sparep-api-server-data-gen
    - text

tests:
  sparep-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - genvalidity-hspec
    - hspec
    - sparep-api
    - sparep-api-gen
