resolver: lts-15.15
packages:
- sparep
extra-deps:
- github: NorfairKing/yamlparse-applicative
  commit: 1d381a4cbc9736a2defc916a93cfcf8000ee7e37
  subdirs:
  - yamlparse-applicative
- github: supki/envparse
  commit: de5944fb09e9d941fafa35c0f05446af348e7b4d
nix:
  packages:
    - zlib
