resolver: lts-15.15
packages:
- sparep-api
- sparep-api-gen
- sparep-api-server
- sparep-client
- sparep-cli
- sparep-web-server
extra-deps:
- github: NorfairKing/yamlparse-applicative
  commit: 1d381a4cbc9736a2defc916a93cfcf8000ee7e37
  subdirs:
  - yamlparse-applicative
- github: supki/envparse
  commit: de5944fb09e9d941fafa35c0f05446af348e7b4d
- github: NorfairKing/cursor-brick
  commit: a7b47b03c8c5525234aaccc0c372e49a80134b9d
  subdirs:
  - cursor-brick
- servant-auth-client-0.4.1.0@sha256:a93f041c3c293eca6e2e2e1a2ed97e58fbbd0e123caeff9e484a68d56272632f,3342

nix:
  packages:
    - zlib
    - haskellPackages.autoexporter
    - killall
