resolver: lts-15.15
packages:
- sparep-api
- sparep-api-gen
- sparep-api-server
- sparep-client
- sparep-client-data
- sparep-server-data
- sparep-server-data-gen
- sparep-data
- sparep-data-gen
- sparep-tui
- sparep-web-server
extra-deps:
- github: NorfairKing/yamlparse-applicative
  commit: 1d381a4cbc9736a2defc916a93cfcf8000ee7e37
  subdirs:
  - yamlparse-applicative
- github: supki/envparse
  commit: de5944fb09e9d941fafa35c0f05446af348e7b4d
- github: NorfairKing/cursor-brick
  commit: a7b47b03c8c5525234aaccc0c372e49a80134b9d
  subdirs:
  - cursor-brick
- github: NorfairKing/appendful
  commit: fac6474856726fc507c42779955a75a12ef98cc7
  subdirs:
  - appendful
  - appendful-persistent
  - genvalidity-appendful
- servant-auth-client-0.4.1.0@sha256:a93f041c3c293eca6e2e2e1a2ed97e58fbbd0e123caeff9e484a68d56272632f,3342
- base16-bytestring-1.0.0.0@sha256:3291e9bd0f018af1855176d9169663261fa60ecced9c68bad6b9cd5a87abd59a,2749
- github: NorfairKing/validity
  commit: 2ef8be2fba631460d770d8cbc7dd67709400fe3d
  subdirs:
  - validity
  - validity-aeson
  - validity-bytestring
  - validity-containers
  - validity-path
  - validity-persistent
  - validity-primitive
  - validity-scientific
  - validity-text
  - validity-time
  - validity-unordered-containers
  - validity-uuid
  - validity-vector
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-criterion
  - genvalidity-hspec
  - genvalidity-hspec-aeson
  - genvalidity-hspec-binary
  - genvalidity-hspec-cereal
  - genvalidity-hspec-hashable
  - genvalidity-hspec-optics
  - genvalidity-hspec-persistent
  - genvalidity-path
  - genvalidity-persistent
  - genvalidity-property
  - genvalidity-scientific
  - genvalidity-text
  - genvalidity-time
  - genvalidity-unordered-containers
  - genvalidity-uuid
  - genvalidity-vector


nix:
  packages:
    - zlib
    - haskellPackages.autoexporter
    - killall
