name:                sparep-api-server-data
version:             0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - appendful
    - appendful-persistent
    - autodocodec
    - password
    - password-instances
    - persistent
    - persistent-sqlite
    - persistent-template
    - sparep-data
    - sparep-data
    - text
    - time
    - validity
    - validity-persistent
    - validity-text
