name:                sparep-data-gen
version:             0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - genvalidity
    - genvalidity-bytestring
    - genvalidity-containers
    - genvalidity-path
    - genvalidity-text
    - genvalidity-time
    - sparep-data
    - text

tests:
  sparep-data-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - genvalidity-hspec
    - genvalidity-hspec-persistent
    - hspec
    - path
    - path-io
    - sparep-data
    - sparep-data-gen
