name:                sparep-server-data-gen
version:             0.0.0.0
github:              "NorfairKing/sparep"
license:             AllRightsReserved
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright (c) 2020 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - QuickCheck
    - bytestring
    - genvalidity
    - genvalidity-persistent
    - genvalidity-text
    - password
    - sparep-data-gen
    - sparep-server-data
    - text

tests:
  sparep-server-data-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - genvalidity-hspec
    - hspec
    - sparep-server-data
    - sparep-server-data-gen
