name:                sparep-server-data
version:             0.0.0.0
github:              "NorfairKing/sparep"
license:             AllRightsReserved
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright (c) 2020 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - appendful
    - appendful-persistent
    - password
    - password-instances
    - persistent
    - persistent-sqlite
    - persistent-template
    - sparep-data
    - sparep-data
    - text
    - time
    - validity
    - validity-persistent
    - validity-text
    - yamlparse-applicative

tests:
  sparep-server-data-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - genvalidity-hspec
    - hspec
    - persistent
    - persistent-sqlite
