name:                sparep-client
version:             0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - servant
    - servant-auth
    - servant-auth-client
    - servant-client
    - servant-client-core
    - text
    - validity
    - validity-text
    - sparep-api
