name: sparep-cli
version: 0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - appendful
  - appendful-persistent
  - autodocodec
  - autodocodec-yaml
  - cookie
  - envparse
  - filelock
  - http-client
  - http-client-tls
  - monad-logger
  - mtl
  - optparse-applicative
  - path
  - path-io
  - persistent
  - persistent-sqlite
  - servant
  - servant-auth-client
  - servant-client
  - sparep-api
  - sparep-api-server-data
  - sparep-client
  - sparep-client-data
  - sparep-data
  - text
  - yaml

executables:
  sparep:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sparep-cli

tests:
  sparep-cli-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - genvalidity
    - genvalidity-sydtest
    - sydtest
    - path
    - path-io
    - servant-client
    - sparep-api
    - sparep-api-server-gen
    - sparep-cli
    - sparep-api-server-data
    - text
