name:                sparep-api-server
version:             0.0.0.0
github:              "NorfairKing/sparep"
license:             AllRightsReserved
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright (c) 2020 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - appendful
    - appendful-persistent
    - bytestring
    - monad-logger
    - mtl
    - password
    - password-instances
    - persistent
    - persistent-sqlite
    - persistent-template
    - servant-auth-server
    - servant-server
    - sparep-api
    - sparep-data
    - sparep-server-data
    - text
    - time
    - wai
    - warp

executables:
  sparep-api-server:
    main: Main.hs
    source-dirs: app/
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
      - sparep-api-server
