name:                sparep-api-server
version:             0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - appendful
    - appendful-persistent
    - autodocodec
    - autodocodec-yaml
    - bytestring
    - envparse
    - jose
    - monad-logger
    - mtl
    - optparse-applicative
    - password
    - password-instances
    - path
    - path-io
    - persistent
    - persistent-sqlite
    - persistent-template
    - servant-auth-server
    - servant-server
    - sparep-api
    - sparep-data
    - sparep-api-server-data
    - text
    - time
    - wai
    - warp
    - yaml

executables:
  sparep-api-server:
    main: Main.hs
    source-dirs: app/
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
      - sparep-api-server
