name:                sparep-data
version:             0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - autodocodec
    - autodocodec-yaml
    - base16
    - bytestring
    - containers
    - cryptohash-sha256
    - directory
    - filepath
    - path
    - path
    - path-io
    - persistent
    - random-shuffle
    - safe
    - text
    - time
    - validity
    - validity-bytestring
    - validity-containers
    - validity-path
    - validity-text
    - validity-time
    - yaml
