name:                sparep-data
version:             0.0.0.0
github:              "NorfairKing/sparep"
license:             AllRightsReserved
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright (c) 2020 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - base16-bytestring >= 1.0
    - bytestring
    - cryptohash-sha256
    - path
    - persistent
    - text
    - time
    - validity
    - validity-bytestring
    - validity-path
    - validity-text
    - validity-time
