name:                sparep-client-data
version:             0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - persistent
  - persistent-sqlite
  - persistent-template
  - safe
  - sparep-api-server-data
  - sparep-data
  - time

tests:
  sparep-client-data-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - genvalidity-sydtest
    - genvalidity-sydtest-persistent
    - sydtest
