name:                sparep-api
version:             0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - appendful
    - autodocodec
    - jose
    - persistent
    - servant
    - servant-auth
    - servant-auth-server
    - sparep-api-server-data
    - sparep-client-data
    - sparep-data
    - text
    - validity
    - validity-text
